import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {/* min-h-screen 确保即使中间的 children 内容很少，Footer 也能被推到屏幕底部以下 */}
        <div className="flex flex-col min-h-screen">
          <main className="flex-grow">{children}</main>
          <Footer /> {/* 2. 将 Footer 放在主体内容下方 */}
        </div>
      </body>
    </html>
  );
}
